language: java
dist: xenial
group: edge

addons:
  postgresql: "9.6"

stages:
  - test
  - deploy

branches:
  only:
    - master
    # release tags
    - /^trellis-microprofile-\d+\.\d+\.\d+$/
    # maintenance branches
    - /^trellis-microprofile-\d+\.\d+\.x$/
    # long-lived branches
    - /branch-.+/

services:
  - postgresql

before_script:
  - psql -c 'create database trellis;' -U postgres

install: skip

env:
  - JOB=check

jobs:
  include:
    # JDK 8
    - name: "Java 8"
      stage: test
      jdk: openjdk8
      script: ./gradlew check install jacocoTestReport --continue --scan -PexternalPgsql

    # JDK 11
    - name: "Java 11"
      stage: test
      jdk: openjdk11
      script: ./gradlew check install -PexternalPgsql

