language: java
dist: xenial
group: edge

addons:
  postgresql: "9.6"

stages:
  - test
  - deploy

services:
  - postgresql

before_script:
  - psql -c 'create database trellis;' -U postgres

env:
  - JOB=check

jobs:
  include:
    # JDK 8
    - name: "Java 8"
      stage: test
      jdk: openjdk8
      env: QUARKUS_EXTERNAL_PGSQL=true
      script: travis_retry ./gradlew check install jacocoRootReport --continue --scan

    # JDK 11
    - name: "Java 11"
      stage: test
      jdk: openjdk11
      script: travis_retry ./gradlew check install

