name: GitHub CI

on:
  push:
    branches:
      - main
      - trellis-microprofile-[0-9]+.[0-9]+.x
  pull_request:
    branches:
      - main


jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: Java ${{ matrix.java }} environment
    needs: [validation]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: trellis
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build javadoc -PexternalPgsql
      env:
        QUARKUS_DATASOURCE_USERNAME: postgres
        QUARKUS_DATASOURCE_PASSWORD: postgres
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost/trellis


